In [13]:
import os
import pandas as pd

In [14]:
from config import input_data_xlsx_filepath, input_data_csv_filepath

In [15]:
def load_data(input_data_xlsx_filepath, input_data_csv_filepath):
    """
    This function loads the input data from an excel file and converts it to a .csv file
    
    Args:
        input_data_xlsx_filepath (str): input .xlsx data file
        input_data_csv_filepath (str): input .csv data file
        
    """
    df = pd.read_excel(input_data_xlsx_filepath, engine='openpyxl')
    df.to_csv(input_data_csv_filepath, index=False)

In [16]:
input_df = pd.read_csv(input_data_csv_filepath)
input_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175402 entries, 0 to 175401
Data columns (total 27 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   date                           175402 non-null  object
 1   product_id                     175402 non-null  object
 2   category                       175402 non-null  object
 3   price                          175402 non-null  float64
 4   sale_price                     46399 non-null   float64
 5   discount_rate                  175402 non-null  float64
 6   product_age                    175402 non-null  int64
 7   product_status                 175402 non-null  object
 8   pct_product_variants_in_stock  175402 non-null  float64
 9   meta_product_revenue           175402 non-null  float64
 10  meta_item_quantity_sold        175402 non-null  int64
 11  meta_product_detail_views      175402 non-null  int64
 12  meta_quantity_added_to_cart    175402 non-null  int64
 13  meta_impressions               175402 non-null  int64
 14  meta_clicks                    175402 non-null  int64
 15  meta_spend                     175402 non-null  float64
 16  google_product_revenue         175402 non-null  float64
 17  google_item_quantity_sold      175402 non-null  int64
 18  google_product_detail_views    175402 non-null  int64
 19  google_quantity_added_to_cart  175402 non-null  int64
 20  google_impressions             175402 non-null  int64
 21  google_clicks                  175402 non-null  int64
 22  google_spend                   175402 non-null  float64
 23  all_product_revenue            175402 non-null  float64
 24  all_item_quantity_sold         175402 non-null  int64
 25  all_product_detail_views       175402 non-null  int64
 26  all_quantity_added_to_cart     175402 non-null  int64
dtypes: float64(9), int64(14), object(4)
memory usage: 36.1+ MB

In [20]:
input_df['date'] = pd.to_datetime(input_df['date'])
val_last_day = input_df['date'].max()
val_first_date = val_last_day - pd.Timedelta(days=7)

In [21]:
val_first_date

Timestamp('2025-05-24 00:00:00')

In [22]:
val_last_day

Timestamp('2025-05-31 00:00:00')

In [24]:
input_df[(input_df['date']>=val_first_date)&(input_df['date']<=val_last_day)]

,date,product_id,category,price,sale_price,discount_rate,product_age,product_status,pct_product_variants_in_stock,meta_product_revenue,...,google_item_quantity_sold,google_product_detail_views,google_quantity_added_to_cart,google_impressions,google_clicks,google_spend,all_product_revenue,all_item_quantity_sold,all_product_detail_views,all_quantity_added_to_cart
11,2025-05-26,000d864b-c092-4160-8eda-e9efe2f6f639,pyjamas,25.99,18.2,0.299731,473,DELETED,0.000000,0.0,...,0,0,0,0,0,0.00,0.000000,0,1,0
15,2025-05-25,003b9e20-4c94-489d-9448-70fc2840219c,Pullis,15.00,9.0,0.599867,197,DELETED,0.000000,0.0,...,0,0,0,0,0,0.00,0.000000,0,8,0
21,2025-05-27,003b9e20-4c94-489d-9448-70fc2840219c,Pullis,15.00,9.0,0.599867,199,DELETED,0.000000,0.0,...,0,0,0,0,0,0.00,0.000000,0,1,0
33,2025-05-24,003b9e20-4c94-489d-9448-70fc2840219c,Pullis,15.00,9.0,0.599867,196,DELETED,0.000000,0.0,...,0,0,0,0,0,0.00,0.000000,0,5,0
42,2025-05-26,003b9e20-4c94-489d-9448-70fc2840219c,Pullis,15.00,9.0,0.599867,198,DELETED,0.000000,0.0,...,0,0,0,0,0,0.00,0.000000,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175372,2025-05-29,fff05380-fae8-44b2-b2ea-f62969ac5706,wide jeans,49.99,NaN,0.000000,99,PARTIALLY_IN_STOCK,0.428571,0.0,...,1,8,3,0,0,0.00,1415.231081,3,64,10
175382,2025-05-28,fff05380-fae8-44b2-b2ea-f62969ac5706,wide jeans,49.99,NaN,0.000000,98,PARTIALLY_IN_STOCK,0.428571,0.0,...,0,9,0,3,0,0.00,0.000000,0,66,3
175386,2025-05-26,fff05380-fae8-44b2-b2ea-f62969ac5706,wide jeans,49.99,NaN,0.000000,96,PARTIALLY_IN_STOCK,0.428571,0.0,...,0,20,5,138,3,12.09,974.809023,2,101,14
175387,2025-05-30,fff05380-fae8-44b2-b2ea-f62969ac5706,wide jeans,49.99,NaN,0.000000,100,PARTIALLY_IN_STOCK,0.428571,0.0,...,0,3,1,0,0,0.00,1633.480380,3,55,10
175391,2025-05-24,fff05380-fae8-44b2-b2ea-f62969ac5706,wide jeans,49.99,NaN,0.000000,94,PARTIALLY_IN_STOCK,0.428571,0.0,...,0,21,1,158,4,11.11,1031.979927,2,109,7